% DO NOT edit this file.

% This file defines the function *test_cases*.
% The `test_cases` function tests the functionality of the *add_2370* function.
% You don't need to understand this file (yet).

function x = test_cases
    x = functiontests(localfunctions);
end

function test_adding_2370(test_case) 
    for i = 1 : 100
        j = add_2370(i);
        verifyEqual(test_case, j, i + 2370)
    end
end
