% DO NOT edit this file.

% This file defines the function *test_cases*.
% The `test_cases` function tests the functionality of the *return_2370* function.
% You don't need to understand this file (yet).

function x = test_cases
    x = functiontests(localfunctions);
end

function test_2370(test_case) 
    x = return_2370();
    verifyEqual(test_case, x, 2370)
end
